name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - develop

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: dev

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: planeja-financeiro-api
          path: artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Show artifact
        run: |
          echo "Deploy DEV"
          echo "Artifact:"
          ls -lh artifact