name: PIPELINE

on:
  push:
    branches:
      - develop
      - release
      - main

  pull_request:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Check Java version
        run: java -version

      - name: Build
        run: ./mvnw clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: planeja-financeiro-api
          path: target/*.jar